# AndroidX
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# JVM
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true

# Kotlin
kotlin.code.style=official

# NDK（CI 里显式安装同版本）
android.ndkVersion=26.1.10909125
